name: drift_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  amplify_storage_s3: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  date_time_format: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
